### PR TITLE
Remove pyc and adding *.pyc to the gitignore

### PR DESCRIPTION
**Pull request by AlexisTM**
Removing PYC files to clean the repo and adding `*.pyc` to the gitignore for good practice.

### CODE REVIEW

**Comment by ninawrong** [comment]
Thanks for submitting the PR.
This is the first PR we ever received :) We will review is on Monday.

**Comment by ninawrong** [comment]
Unrelated note, we have been initiating an [AUTHOR.md ](https://github.com/generalized-intelligence/GAAS/blob/master/AUTHORS.md) to send our appreciation to our earliest contributors. Would you mind if we make a badge for you with your name on it, linking to your github profile?
If I can get your permission to do so, we will start designing a badge for you on Monday :) 
It's nothing fancy but our team is very excited to receive our first PR!

**Comment by AlexisTM** [comment]
I am happy to be have started the first PR and would be happy to be added to the Author.md.

Once I really dig in, I could do other PRs.

**Comment by ninawrong** [comment]
We have featured you on our [AUTHORS.md](https://github.com/generalized-intelligence/GAAS/blob/master/AUTHORS.md) 
Good work!

> I am happy to be have started the first PR and would be happy to be added to the Author.md.
> 
> Once I really dig in, I could do other PRs.

**Pull request merged**
